#!/bin/sh

APPDIR=$(dirname "$0")

export PATH="${APPDIR}/usr/bin"
export LD_LIBRARY_PATH="${APPDIR}/lib/x86_64-linux-gnu"
export FONTCONFIG_FILE="${APPDIR}/etc/fonts/fonts.conf"

cd "${APPDIR}"
exec "${APPDIR}/firefox-app/firefox" "$@"
