#!/bin/sh

APPDIR=$(dirname "$0")

export PATH="${APPDIR}/usr/bin:${PATH}"

exec "${APPDIR}/firefox-app/ld-linux-x86-64.so.2" --inhibit-cache --library-path "${APPDIR}/lib/x86_64-linux-gnu" "${APPDIR}/firefox-app/firefox-bin" "$@"
