name: Release
on:
#   schedule:
#     - cron: "5 */12 * * *"
  push:
    branches:
      - "main"
jobs:
    Release:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3.5.3

        - name: Build archive
          run: |
            set -e

            docker build . -f Dockerfile.BuildLinux -t portable-firefox:latest
            VERSION=$(docker run --rm portable-firefox:latest --version)
            export VERSION_NUMBER=$(echo ${VERSION} | sed 's/Mozilla Firefox //g' | sed 's/\r//')
            docker create --name portable-firefox portable-firefox:latest
            docker cp portable-firefox:/firefox.tar.gz portable-firefox-linux64-${VERSION_NUMBER}.tar.gz

        - uses: "marvinpinto/action-automatic-releases@latest"
          with:
            title: Firefox linux64 ${{ env.VERSION_NUMBER }}
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            prerelease: false
            draft: false 
            files: |
              portable-firefox-linux64-${{ env.VERSION_NUMBER }}.tar.gz
