name: Release
on:
#   schedule:
#     - cron: "5 */12 * * *"
  push:
    branches:
      - "main"
jobs:
    Release:
        runs-on: ubuntu-latest
        concurrency: release
        steps:
        - uses: actions/checkout@v3.5.3

        - name: Generate version suffix
          run: echo "VERSION_SUFFIX=01" >> $GITHUB_ENV

        - name: Build linux64 archive
          run: |
            set -e

            docker build . -f Dockerfile.BuildLinux -t portable-firefox:latest
            VERSION=$(docker run --rm portable-firefox:latest --version)
            VERSION_NUMBER=$(echo ${VERSION} | sed 's/Mozilla Firefox //g' | sed 's/\r//')
            docker create --name portable-firefox portable-firefox:latest
            docker cp portable-firefox:/firefox.tar.gz portable-firefox-linux64-${VERSION_NUMBER}.tar.gz
            echo "VERSION_NUMBER=${VERSION_NUMBER}" >> $GITHUB_ENV

        - uses: mukunku/tag-exists-action@v1.3.0
          id: checkReleaseExists
          with: 
            tag: v${{ env.VERSION_NUMBER }}${{ env.VERSION_SUFFIX }}

        - uses: "marvinpinto/action-automatic-releases@latest"
          if: ${{ steps.checkReleaseExists.outputs.exists }} == 'false'
          with:
            title: Firefox v${{ env.VERSION_NUMBER }}${{ env.VERSION_SUFFIX }}
            automatic_release_tag: v${{ env.VERSION_NUMBER }}${{ env.VERSION_SUFFIX }}
            prerelease: false
            draft: false 
            files: |
              portable-firefox-linux64-${{ env.VERSION_NUMBER }}.tar.gz
            repo_token: "${{ secrets.GITHUB_TOKEN }}"

        - name: Replace FirefoxVersion
          if: ${{ steps.checkReleaseExists.outputs.exists }} == 'false'
          run: |
            set -e
            sed 's/$(FirefoxVersion)/${{ env.VERSION_NUMBER }}/g' -i packages/nuget/PortableFirefox/PortableFirefox/PortableFirefox.csproj
            sed 's/$(FirefoxVersion)/${{ env.VERSION_NUMBER }}/g' -i packages/nuget/PortableFirefox/PortableFirefox/build/PortableFirefox.targets

        - name: Replace VersionSuffix
          if: ${{ steps.checkReleaseExists.outputs.exists }} == 'false'
          run: |
            set -e
            sed 's/$(VersionSuffix)/${{ env.VERSION_SUFFIX }}/g' -i packages/nuget/PortableFirefox/PortableFirefox/PortableFirefox.csproj
            sed 's/$(VersionSuffix)/${{ env.VERSION_SUFFIX }}/g' -i packages/nuget/PortableFirefox/PortableFirefox/build/PortableFirefox.targets
    
        - name: Setup .NET
          if: ${{ steps.checkReleaseExists.outputs.exists }} == 'false'
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 7.0.x

        - name: Pack
          if: ${{ steps.checkReleaseExists.outputs.exists }} == 'false'
          working-directory: packages/nuget/PortableFirefox
          run: dotnet pack PortableFirefox --configuration Release

        - name: Publish nuget
          if: ${{ steps.checkReleaseExists.outputs.exists }} == 'false'
          working-directory: packages/nuget/PortableFirefox
          run: dotnet nuget push PortableFirefox/bin/Release/PortableFirefox.*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://www.nuget.org --skip-duplicate
